import type { DebriefQuestion } from "./types";

/**
 * CAMTS mapping scaffold: replace `CAMTS-TBD-*` references with your official
 * crosswalk identifiers when available.
 */
export const DEBRIEF_QUESTIONS: DebriefQuestion[] = [
  {
    id: "clinical_cabin_temp_in_range",
    module: "Clinical",
    prompt:
      "Was cabin temperature maintained between 50°F and 95°F (10°C to 35°C) while patient was on board?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-ENV-01",
  },
  {
    id: "clinical_cabin_temp_out_of_range_detail",
    module: "Clinical",
    prompt:
      "If no, document mitigation steps and any adverse effects on patient or crew.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_cabin_temp_in_range",
      equals: "No",
    },
    standardRef: "CAMTS-12-CLIN-ENV-01A",
  },
  {
    id: "clinical_failed_restraint_use",
    module: "Clinical",
    prompt:
      "Any patient physical/chemical restraint event that deviated from protocol or resulted in injury?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-SAFE-02",
  },
  {
    id: "clinical_failed_restraint_use_detail",
    module: "Clinical",
    prompt: "If yes, describe restraint variance, injury, and immediate actions.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_failed_restraint_use",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-SAFE-02A",
  },
  {
    id: "clinical_advanced_airway_management",
    module: "Clinical",
    prompt:
      "Was advanced airway management performed (intubation, surgical airway, or failed attempt)?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-OUT-03",
  },
  {
    id: "clinical_advanced_airway_waveform_capnography",
    module: "Clinical",
    prompt:
      "If yes, was waveform capnography used and documented for airway confirmation?",
    type: "yes_no",
    required: true,
    followUpWhen: {
      questionId: "clinical_advanced_airway_management",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-OUT-03A",
  },
  {
    id: "clinical_advanced_airway_confirmation_methods",
    module: "Clinical",
    prompt:
      "If yes, list all airway confirmation methods and final placement status.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_advanced_airway_management",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-OUT-03B",
  },
  {
    id: "clinical_unplanned_extubation",
    module: "Clinical",
    prompt: "Did an unplanned extubation occur during transport?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-OUT-04",
  },
  {
    id: "clinical_unplanned_extubation_detail",
    module: "Clinical",
    prompt: "If yes, describe event timeline, suspected cause, and patient impact.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_unplanned_extubation",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-OUT-04A",
  },
  {
    id: "clinical_discharged_within_24h",
    module: "Clinical",
    prompt:
      "Was patient discharged within 24 hours after critical care / ALS transport?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-OUT-05",
  },
  {
    id: "clinical_discharged_within_24h_necessity_review",
    module: "Clinical",
    prompt:
      "If yes, document utilization review and medical necessity rationale for level of care.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_discharged_within_24h",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-OUT-05A",
  },
  {
    id: "clinical_transport_without_iv_access",
    module: "Clinical",
    prompt: "Was patient transported without patent IV/IO access on critical care/ALS mission?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-OUT-06",
  },
  {
    id: "clinical_transport_without_iv_access_justification",
    module: "Clinical",
    prompt: "If yes, provide clinical justification and risk mitigation.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_transport_without_iv_access",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-OUT-06A",
  },
  {
    id: "clinical_cardiac_respiratory_arrest",
    module: "Clinical",
    prompt:
      "Did cardiac/respiratory arrest occur during transport or shortly post-handover?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-OUT-07",
  },
  {
    id: "clinical_cardiac_respiratory_arrest_detail",
    module: "Clinical",
    prompt: "If yes, describe timeline, interventions, and outcome.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_cardiac_respiratory_arrest",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-OUT-07A",
  },
  {
    id: "clinical_blood_product_administration",
    module: "Clinical",
    prompt: "Were blood products administered pre-hospital?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-SPEC-08",
  },
  {
    id: "clinical_blood_product_administration_detail",
    module: "Clinical",
    prompt:
      "If yes, document cold-chain maintenance, transfusion monitoring, and any reaction.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_blood_product_administration",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-SPEC-08A",
  },
  {
    id: "clinical_invasive_line_placement",
    module: "Clinical",
    prompt:
      "Any invasive line/procedure performed in transport environment (chest tube, central line, arterial line)?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-SPEC-09",
  },
  {
    id: "clinical_invasive_line_placement_detail",
    module: "Clinical",
    prompt: "If yes, document indication, sterility/process, and immediate result.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_invasive_line_placement",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-SPEC-09A",
  },
  {
    id: "clinical_significant_medication_error",
    module: "Clinical",
    prompt: "Any significant medication error or near miss?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-SPEC-10",
  },
  {
    id: "clinical_significant_medication_error_detail",
    module: "Clinical",
    prompt: "If yes, describe deviation, contributing factors, and mitigation.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_significant_medication_error",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-SPEC-10A",
  },
  {
    id: "clinical_diversion_or_declined_after_acceptance",
    module: "Clinical",
    prompt: "Was mission diverted or declined after initial acceptance?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-OPS-11",
  },
  {
    id: "clinical_diversion_or_declined_detail",
    module: "Clinical",
    prompt: "If yes, document clinical-operational rationale and communication chain.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_diversion_or_declined_after_acceptance",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-OPS-11A",
  },
  {
    id: "clinical_scene_time_over_20_min",
    module: "Clinical",
    prompt:
      "For trauma/STEMI/stroke missions, did scene time exceed 20 minutes (or program threshold)?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-12-CLIN-OPS-12",
  },
  {
    id: "clinical_scene_time_over_20_min_reason",
    module: "Clinical",
    prompt:
      "If yes, document reason for prolonged scene time and impact on care timeline.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "clinical_scene_time_over_20_min",
      equals: "Yes",
    },
    standardRef: "CAMTS-12-CLIN-OPS-12A",
  },
  {
    id: "clinical_qm_event_datetime",
    module: "Clinical",
    prompt: "Record event and debrief date/time (ISO or local with timezone).",
    type: "text",
    required: true,
    standardRef: "CAMTS-12-QM-REQ-01",
  },
  {
    id: "clinical_qm_attendees",
    module: "Clinical",
    prompt: "List attendees by name and role/function.",
    type: "textarea",
    required: true,
    standardRef: "CAMTS-12-QM-REQ-02",
  },
  {
    id: "clinical_qm_root_cause",
    module: "Clinical",
    prompt: "Root cause analysis / identified problem areas.",
    type: "textarea",
    required: true,
    standardRef: "CAMTS-12-QM-REQ-03",
  },
  {
    id: "clinical_qm_corrective_action",
    module: "Clinical",
    prompt:
      "Corrective action plan (education, policy/process update, equipment change).",
    type: "textarea",
    required: true,
    standardRef: "CAMTS-12-QM-REQ-04",
  },
  {
    id: "clinical_qm_followup_evaluation",
    module: "Clinical",
    prompt:
      "Follow-up evaluation plan to verify corrective action effectiveness.",
    type: "textarea",
    required: true,
    standardRef: "CAMTS-12-QM-REQ-05",
  },

  {
    id: "aviation_weather_impact",
    module: "Aviation",
    prompt: "Did weather impact route, altitude, or acceptance?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-TBD-AV-01",
  },
  {
    id: "aviation_weather_impact_detail",
    module: "Aviation",
    prompt: "If yes, describe weather factors and decisions made.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "aviation_weather_impact",
      equals: "Yes",
    },
    standardRef: "CAMTS-TBD-AV-01A",
  },
  {
    id: "aviation_aircraft_discrepancy",
    module: "Aviation",
    prompt: "Any aircraft discrepancy affecting mission readiness?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-TBD-AV-02",
  },
  {
    id: "aviation_aircraft_discrepancy_detail",
    module: "Aviation",
    prompt: "If yes, describe discrepancy and corrective action.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "aviation_aircraft_discrepancy",
      equals: "Yes",
    },
    standardRef: "CAMTS-TBD-AV-02A",
  },
  {
    id: "aviation_fatigue_concern",
    module: "Aviation",
    prompt: "Any fatigue or human factor concern identified?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-TBD-AV-03",
  },
  {
    id: "aviation_fatigue_concern_detail",
    module: "Aviation",
    prompt: "If yes, what mitigations were used?",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "aviation_fatigue_concern",
      equals: "Yes",
    },
    standardRef: "CAMTS-TBD-AV-03A",
  },

  {
    id: "comm_center_dispatch_delay",
    module: "Communication Center",
    prompt: "Any dispatch or communication delay that impacted mission flow?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-TBD-COMM-01",
  },
  {
    id: "comm_center_dispatch_delay_detail",
    module: "Communication Center",
    prompt: "If yes, provide timeline and source of delay.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "comm_center_dispatch_delay",
      equals: "Yes",
    },
    standardRef: "CAMTS-TBD-COMM-01A",
  },
  {
    id: "comm_center_failed_contact",
    module: "Communication Center",
    prompt: "Were there any failed contact attempts with crew/facility/agency?",
    type: "yes_no",
    required: true,
    standardRef: "CAMTS-TBD-COMM-02",
  },
  {
    id: "comm_center_failed_contact_detail",
    module: "Communication Center",
    prompt: "If yes, describe parties, duration, and escalation path.",
    type: "textarea",
    required: true,
    followUpWhen: {
      questionId: "comm_center_failed_contact",
      equals: "Yes",
    },
    standardRef: "CAMTS-TBD-COMM-02A",
  },
  {
    id: "comm_center_client_type",
    module: "Communication Center",
    prompt: "Primary client type for this trip",
    type: "select",
    required: true,
    options: [
      "Healthcare Facility",
      "Fire",
      "EMS",
      "Law Enforcement",
      "SAR",
      "Ski Patrol",
      "Military",
      "Other",
    ],
    standardRef: "CAMTS-TBD-COMM-03",
  },
  {
    id: "comm_center_client_type_other",
    module: "Communication Center",
    prompt: "If Other, specify client type.",
    type: "text",
    required: true,
    followUpWhen: {
      questionId: "comm_center_client_type",
      equals: "Other",
    },
    standardRef: "CAMTS-TBD-COMM-03A",
  },
];
